artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/Ronak-Sah/Datafiles/raw/refs/heads/main/translate.zip
  
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

tokenization_trainer:
  root_dir : artifacts/tokenization_trainer
  data_path : "artifacts/data_ingestion/translation/train.csv"
  tokenizer_path : "artifacts/tokenization_trainer/tokenizer"


model_trainer:
  root_dir : artifacts/model_trainer
  data_path : "artifacts/data_ingestion/translation/train.csv"
  tokenizer_path : "artifacts/tokenization_trainer/tokenizer"


model_evaluation:
  root_dir : artifacts/model_evaluation
  data_path : artifacts/data_ingestion/translation/train.csv
  model_path : artifacts/model_trainer/transformer_model.pth
  tokenizer_path : artifacts/tokenization_trainer/tokenizer
  metric_file_name : artifacts/model_evaluation/metrics.csv
   