artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/Ronak-Sah/Datafiles/raw/refs/heads/main/translation.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

tokenization_trainer:
  root_dir : artifacts/tokenization_trainer
  data_path : "artifacts/data_ingestion/translation/train.csv"
  tokenizer_path : "artifacts/tokenization_trainer/tokenizer"


model_trainer:
  root_dir : artifacts/model_trainer
  data_path : "artifacts/data_ingestion/translation/train.csv"
  tokenizer_path : "artifacts/tokenization_trainer/tokenizer"
   